apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: checkout-e2e-tech-test
  description: Component for checkout-e2e-tech-test
  annotations:
    circleci.com/project-slug: github/newsuk/checkout-e2e-tech-test
    backstage.io/source-location: url:https://github.com/newsuk/checkout-e2e-tech-test/
    github.com/team-slug: newsuk/checkout-e2e-tech-test
    backstage.io/productivity-hub-metrics-enabled: 'true'
  tags:
    - bu:newsuk
spec:
  type: service
  lifecycle: production
  owner: nuk